server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/departments/**
        - id: document
          uri: http://localhost:8082
          predicates:
            - Path=/api/documents/**, /api/categories/**

jwt:
  secret: ${JWT_SECRET}
  tokenPrefix: "Bearer "
  headerName: "Authorization"